### ISSUE TITLE
file history.csv not found

### ISSUE THREAD

**Issue by benoitchazoule** [AlexiCoard/where_to_eat#1]
We have this error on the first launch of script:
Looping over 17 restaurants...
Traceback (most recent call last):
  File "yum.py", line 98, in <module>
    already_visited_restaurants = find_last_visited_restaurants(int(args.limit))
  File "yum.py", line 29, in find_last_visited_restaurants
    with open(HISTORY_FILE, 'r+') as visited_restaurants:
FileNotFoundError: [Errno 2] No such file or directory: 'history.csv'

**Comment by benoitchazoule** [comment]
issue fixed by merge of branch feature/issue-1-FixCreationOfHistoryFile
